import {Bell,FileWarning,ClipboardCheck,CircleHelp,UserRound,LayoutDashboard,MonitorSmartphone,Brain,Mic,CalendarClock,Heart,ShieldAlert,Users,BookOpen,Music2,Settings,BarChart3,Camera,HeartHandshake,Clock} from "lucide-react";
import {useTranslation} from "react-i18next"; import {useNavigate} from "react-router-dom"; import {speak} from "../services/tts";
export default function Home(){const {t}=useTranslation(),nav=useNavigate(),name=localStorage.getItem("carehub-name")||"Meena Sharma";return <>
<section className="home-head"><div><span className="eyebrow">CARE HUB • GOOD MORNING</span><h1>{t("welcomeBack")}, {name}</h1><p>One calm step at a time. What would you like to do?</p></div><button className="avatar avatar-button" onClick={()=>nav('/settings')}><UserRound/></button></section>
<section className="daily-banner"><div><span className="eyebrow">YOUR DAY</span><b>3 of 5 care moments complete</b><div className="progress"><i style={{width:'60%'}}/></div></div><button onClick={()=>nav('/my-day')}><Heart/> My Day</button></section>
<section className="four-actions"><Action icon={<Bell/>} title={t("meds")} subtitle="2 reminders today" click={()=>nav("/meds")}/><Action icon={<FileWarning/>} title={t("issue")} subtitle="Share how you feel" click={()=>nav("/issue")}/><Action icon={<ClipboardCheck/>} title={t("plan")} subtitle="3 of 5 complete" click={()=>nav("/plan")}/><Action icon={<CircleHelp/>} title={t("help")} subtitle="Care tips & support" click={()=>nav("/help")}/></section>
<div className="quick-heading"><h2>More ways to help</h2><button onClick={()=>nav('/notifications')}><Bell/> Notifications</button></div>
<div className="feature-grid"><Feature icon={<Brain/>} title="Cognitive Games" text="Short, friendly activities" click={()=>nav('/games')}/><Feature icon={<Mic/>} title="Voice / Ask" text="Speak instead of typing" click={()=>nav('/voice')}/><Feature icon={<CalendarClock/>} title="Reminders" text="Medicine & routines" click={()=>nav('/reminders')}/><Feature icon={<Users/>} title="Care Team" text="Trusted people" click={()=>nav('/care-team')}/><Feature icon={<ShieldAlert/>} title="Safety" text="Quick help & contacts" click={()=>nav('/safety')}/><Feature icon={<BookOpen/>} title="Resources" text="Learn & connect" click={()=>nav('/resources')}/><Feature icon={<Music2/>} title="90s Music" text="Familiar retro sounds" click={()=>nav('/music')}/><Feature icon={<Heart/>} title="About Me" text="Preferences & routines" click={()=>nav('/about-me')}/><Feature icon={<Camera/>} title="Memory Album" text="Photos & stories" click={()=>nav('/memories')}/><Feature icon={<Clock/>} title="Family Timeline" text="Today at a glance" click={()=>nav('/timeline')}/><Feature icon={<HeartHandshake/>} title="What Helps" text="Personal comfort cues" click={()=>nav('/what-helps')}/></div>
<div className="secondary-row"><button onClick={()=>nav("/dashboard")}><LayoutDashboard/> {t("dashboard")}</button><button onClick={()=>nav("/reports")}><BarChart3/> Reports</button><button onClick={()=>nav("/kiosk")}><MonitorSmartphone/> {t("kiosk")}</button><button onClick={()=>nav("/settings")}><Settings/> Settings</button></div>
</>}
function Action({icon,title,subtitle,click}:{icon:any;title:string;subtitle:string;click:()=>void}){return <button className="action-card" onClick={()=>{speak(`${title}. ${subtitle}`);click()}}><span>{icon}</span><b>{title}</b><small>{subtitle}</small></button>}
function Feature({icon,title,text,click}:{icon:any;title:string;text:string;click:()=>void}){return <button className="feature-card" onClick={()=>{speak(`${title}. ${text}`);click()}}><span>{icon}</span><div><b>{title}</b><small>{text}</small></div></button>}
