import {useEffect,useState} from "react";
import {Activity,AlertTriangle,CheckCircle2,Cloud,Users,TrendingUp,CalendarClock,ShieldCheck} from "lucide-react";
import {db} from "../db/database"; import type {CareLog,CarePlanItem,Medicine} from "../types"; import {useNavigate} from "react-router-dom";
export default function Dashboard(){const [meds,setMeds]=useState<Medicine[]>([]),[plan,setPlan]=useState<CarePlanItem[]>([]),[logs,setLogs]=useState<CareLog[]>([]);const nav=useNavigate();useEffect(()=>{Promise.all([db.medicines.toArray(),db.carePlan.toArray(),db.careLogs.toArray()]).then(([m,p,l])=>{setMeds(m);setPlan(p);setLogs(l)})},[]);const medPct=meds.length?Math.round(meds.filter(x=>x.status==='taken').length/meds.length*100):0;const planPct=plan.length?Math.round(plan.filter(x=>x.completed).length/plan.length*100):0;return <>
<div className="dashboard-head"><div><span className="eyebrow">CAREGIVER / HEALTH WORKER</span><h1>Caregiver Dashboard</h1><p>Clear signals, simple trends and safe next steps.</p></div><span className="status-pill"><Cloud/> {navigator.onLine?'Ready':'Offline'}</span></div>
<section className="patient-banner"><div className="patient-photo">MS</div><div><span className="eyebrow">PATIENT</span><h2>Meena Sharma</h2><p>Care recipient • Today</p></div><button onClick={()=>nav('/reports')}><TrendingUp/> View report</button></section>
<div className="dash-grid"><Stat icon={<Users/>} n="1" label="Patient"/><Stat icon={<CheckCircle2/>} n={`${medPct}%`} label="Medicine completion"/><Stat icon={<Activity/>} n={`${planPct}%`} label="Care plan"/><Stat icon={<AlertTriangle/>} n={`${logs.length}`} label="Logged events"/></div>
<section className="dash-panel"><div className="panel-heading"><div><h2>Today at a glance</h2><p className="muted">A supportive summary, not a diagnosis.</p></div><span className="safe-tag"><ShieldCheck/> Safe wording</span></div><div className="trend-row"><Trend label="Medicine" value={medPct}/><Trend label="Care plan" value={planPct}/><Trend label="Daily routine" value={Math.min(100,Math.max(25,planPct+15))}/></div></section>
<section className="dash-panel"><div className="panel-heading"><div><h2>Upcoming</h2><p className="muted">Keep the next action visible.</p></div></div><div className="upcoming"><CalendarClock/><div><b>08:00 PM • Medicine</b><p>Medicine B — 1 tablet</p></div><span>Pending</span></div><div className="upcoming"><CalendarClock/><div><b>Tomorrow • Care check-in</b><p>Family caregiver check-in</p></div><span>Planned</span></div></section>
<section className="dash-panel"><div className="panel-heading"><div><h2>Recent events</h2><p className="muted">Review what the patient has logged.</p></div></div>{logs.length?<div className="alert-list">{logs.slice(-5).reverse().map((l,i)=><div className="alert-row" key={i}><AlertTriangle/><div><b>{friendly(l.category)}</b><p>{l.note||'No additional note.'}</p></div></div>)}</div>:<p className="muted">No recent issues recorded.</p>}</section>
</>}
function Stat({icon,n,label}:{icon:any;n:string;label:string}){return <div className="stat-card">{icon}<b>{n}</b><small>{label}</small></div>}
function Trend({label,value}:{label:string;value:number}){return <div className="trend"><div><b>{label}</b><span>{value}%</span></div><div className="trend-track"><i style={{width:`${value}%`}}/></div></div>}
function friendly(s:string){return s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
